# Generated by Django 3.2.7 on 2021-09-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Is canceled')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
