# Generated by Django 3.2.7 on 2021-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210923_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_canceled',
        ),
    ]
